# Generated by Django 4.2.3 on 2023-07-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('numeric_code', models.CharField(max_length=3, null=True)),
                ('iso2', models.CharField(max_length=2, null=True)),
                ('phonecode', models.CharField(max_length=255, null=True)),
                ('capital', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('currency_name', models.CharField(max_length=255, null=True)),
                ('currency_symbol', models.CharField(max_length=255, null=True)),
                ('tld', models.CharField(max_length=255, null=True)),
                ('native', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=255, null=True)),
                ('subregion', models.CharField(max_length=255, null=True)),
                ('timezones', models.TextField()),
                ('translations', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('emoji', models.CharField(max_length=191, null=True)),
                ('emojiU', models.CharField(max_length=191, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
                ('wikiDataId', models.CharField(db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
            ],
        ),
    ]
